const ErrorEnum = Object.freeze({
  error_message_invalid_phone_number_or_password: 'Invalid password or number',
  error_message_invalid_number_or_code: 'Invalid number or code',
  error_message_cant_send_code: 'Can\'t send code',
  error_message_already_signin: 'Already verified. Please reload page',
  error_message_invalid_code: 'Invalid code',
  nothing_updated: 'Nothing updated',
  nothing_deleted: 'Nothing deleted',
  error_message_phone_number_already_busy: {phoneNumber: "Phone number already busy"},
  user_created: "User created",
  driver_created: "Driver created",
  error_message_driver_already_busy: "Driver already busy",
  error_message_email_already_busy: "Email already busy",
  error_message_number_already_busy: "Number already busy",
  user_updated: 'User updated',
  driver_updated: 'Driver updated',
  user_deleted: 'User deleted',
  driver_deleted: 'Driver deleted',
  error_message_not_permission_update_country: 'You don\'t have permission to update country',
  country_created: 'Country created',
  error_message_country_already_exist: 'Country already exist',
  error_message_city_already_exist: 'City already exist',
  country_updated: 'Country updated',
  country_deleted: 'Country deleted',
  city_created: 'City created',
  city_updated: 'City updated',
  city_deleted: 'City deleted',
  route_created: 'Route created',
  route_deleted: 'Route deleted',
  partner_created: 'Partner created',
  partner_deleted: 'Partner deleted',
  partner_updated: 'Partner updated',
  service_created: 'Service created',
  service_updated: 'Service updated',
  service_deleted: 'Service deleted',
  ticket_created: 'Ticket created',
  ticket_updated: 'Ticket updated',
  ticket_deleted: 'Ticket deleted',
  passenger_deleted: 'Passenger deleted',
  ticket_detail_deleted: 'Ticket detail deleted',
  error_message_available_count_error: 'Available count error',
  error_message_not_authorized: 'You aren\'t authorized',
  delivery_service_created: 'Order created',
  delivery_service_updated: 'Order updated',
  deliveryService_deleted: 'Order deleted',
  error_message_no_such_partner: 'No such partner',
  error_message_no_such_partner_branch: 'No such branch',
  error_message_no_such_driver: 'No such driver',
})

export default ErrorEnum;
